### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by TohruMKDM** [samyeyo/LuaRT#1]
Would it be possible for the UI module of LuaRT to add a object that could be used for embedding videos? and perhaps an audio player as well. Some project I want to do requires this and I would love to be able to do it with LuaRT.
I don't know anything about UI's so excuse me if this proposal comes off as outlandish.

**Comment by samyeyo** [comment]
Hi TohruMKDM,

Thank you for your interest in LuaRT.
This kind of feature is more for a third party library than for the ui module which brings minimal Windows GUI functionalities. 
The cost in terms or executable size is also too high. 
There is other component missing (progress bar and canvas for example) that have highest priority.

Regards,
