### ISSUE TITLE
Where is the `ui.dll` file stored? 

### ISSUE THREAD

**Issue by Dismalitie** [samyeyo/LuaRT#126]
I'm trying to a make my own app and I need the DLL to compile with `rtc.exe`, but I just can't find it. I've looked in LuaRT's module folder, I've looked in LuaRT-Studio's module folder and I just can't find it. If you could provide a link or path to the file on GitHub, that would be really helpful!
Thanks! 👍

**Comment by samyeyo** [comment]
Hi Dismalitie,

The `ui` module is not a standalone module. It is bundled within the `wluart.exe` interpreter (see https://luart.org/doc/toolchain/interpreter.html)

If you want to compile a desktop application with `rtc` you must use the `-w` switch to tell the compiler to use the `wluart.exe` interpreter, or using `wrtc` by selecting the `Windows Desktop` subsystem.

**Comment by Dismalitie** [comment]
Thanks!
