### ISSUE TITLE
When setting an image, it resizes it even if you already set the size

### ISSUE THREAD

**Issue by xFN10x** [samyeyo/LuaRT#151]
in the program im writing, i have a Picture that sets it to a certain thing every time you do something, but the images were too small, so i made the image twice the size. But when i set it, it goes back to the orignal size, then i have to put it back again. This is very slow, and you can see how slow it is if you use it.

**Comment by xFN10x** [comment]
it still does it

**Comment by samyeyo** [comment]
Yes you are right. In fact when using `Picture:load()` the size of the loaded Picture will be the size of the image.
In next version, the `Picture:load()` method will accept two optional arguments to specify the wanted width and height
