### ISSUE TITLE
Drag performance lags when dragged with altdrag application

### ISSUE THREAD

**Issue by u9g** [samyeyo/LuaRT#197]
Hi, would it be possible to fix how dragging any luart windows using the alt-drag program is kind of laggy, but dragging normal applications isn't?

https://streamable.com/zbbf6c

**Comment by samyeyo** [comment]
Hi u9g,

I just tried by installing AltDrag.
Honestly I don't see any perceptible difference.

I don't know how AltDrag works, but it seems to use the hooking technique. This probably interferes with the event handling of the `ui` module. From what I was able to analyze, the moving window emits a significant number of `Window:onMove()` events using AltDrag, this is probably why you are experiencing lag.

In this case, it is not a bug related to LuaRT

**Comment by u9g** [comment]
> Hi u9g,
> 
> I just tried by installing AltDrag. Honestly I don't see any perceptible difference.

When you tried it, did you hold alt and drag the window by moving it after clicking in the middle of the window or were you just dragging the top bar still?

> 
> I don't know how AltDrag works, but it seems to use the hooking technique. This probably interferes with the event handling of the `ui` module. From what I was able to analyze, the moving window emits a significant number of `Window:onMove()` events using AltDrag, this is probably why you are experiencing lag.
> 
> In this case, it is not a bug related to LuaRT

I understand, but it has to be a bug related to LuaRT considering that this doesn't happen with most other normal windows.
