### ISSUE TITLE
Broken `require` function with non built-in DLL packages in root modules

### ISSUE THREAD

**Issue by noobpen** [samyeyo/LuaRT#215]
`require` tries to call packages incorrectly:
```
\lrt/modules/crpyto/crpyto.dll
```

**Comment by noobpen** [comment]
It appears that after i uninstalled LfW, it deleted `LUA_PATH`, and it didn't return after installing luaRT.

**Comment by noobpen** [comment]
when i was making a script with `net` and `crypto` libs, it said the libs didn't exist. altough they were in my luaRT root.

**Comment by noobpen** [comment]
`luart.exe` doesn't find the `dll`s for these libs, while it gets the right path, it is incorrectly calling it.

**Comment by noobpen** [comment]
I did how the docs showed it:
```lua
local net = require "net"
local crypto = require "crpyto"
local ui = require "ui"

local test = Object{}
print(test)
```

**Comment by noobpen** [comment]
It errors at line 2, saying there is no `crypto` package.

**Comment by noobpen** [comment]
commenting the second line fixes it.

**Comment by samyeyo** [comment]
Do you have the environment variable LUA_PATH defined ?
If so, try to suppress it, it should remove this issue

**Comment by noobpen** [comment]
Appears to have fixed itself.
