### ISSUE TITLE
io.read() for reading user input freezes the program unrecoverably

### ISSUE THREAD

**Issue by FatalError42O** [samyeyo/LuaRT#219]
io.read() as used here:
https://stackoverflow.com/questions/12069109/getting-input-from-the-user-in-lua
will freeze the program putting it into an unrecoverable state without throwing an error.
This makes user input input seperate from the ui impossible.

**Comment by samyeyo** [comment]
io.read() is a blocking function from the standard library. It's not the usual way to get user input for Desktop applications.

**Comment by samyeyo** [comment]
io.read() is a blocking function from the standard library. It's not the usual way to get user input for Desktop applications.
