### ISSUE TITLE
Удаление LuaRT

### ISSUE THREAD

**Issue by Drus566** [samyeyo/LuaRT#36]
Приветсвтую! 
При удалении LuaRT удаляется целиком все содержимое папки. А что если пользователь установил напрямую в корень диска ? Удалятся также все файлы с диска C. 
Думаю надо поправить)

**Comment by samyeyo** [comment]
Please try to use english when submitting issues :)

You are right, the LuaRT uninstaller removes the entire folder where LuaRT has been installed. It's the common recommended way to uninstall a Windows program (the same issue is found with Windows MSI based installers).

I will work on a workaround. Thank you for the feedback.

**Comment by samyeyo** [comment]
Implemented in LuaRT 1.2.0 ✅
