### ISSUE TITLE
Compiler error (dwmapi.h is not uptodate on Mingw-w64)

### ISSUE THREAD

**Issue by samyeyo** [samyeyo/LuaRT#38]
Window round corners on Windows 11 is a recent feature introduced in latest release of the Windows SDK.
`Dwmapi.h` distributed with Mingw-w64 is quite old, hence the error during compilation

**Comment by samyeyo** [comment]
Fixed in commit https://github.com/samyeyo/LuaRT/commit/ca0566290fdd24a52d3296dfeaa083916edb04c3

**Comment by RSupreme4** [comment]
Works now, thanks!
