### ISSUE TITLE
Questions about how `net.Https:get` method is designed

### ISSUE THREAD

**Issue by greatwolf** [samyeyo/LuaRT#63]
Couple things I noticed about its usage and limitation I don't really like:

- There's no way to specify extra headers for the request
- The response returned is clunky and awkward. Sometimes you get a string and sometimes a file.

For the second point especially, it seems to make more sense to just always return whatever response as a string for the following reasons:

- To avoid littering whatever directory it's dumping the response to.
- For usage consistency. The way it's currently designed means the user will have to write code to check what type the response is and handle it differently depending on whether it's a string or file.
- The user can always write the response to a file if he so desires.
- This is more inline with how http api is designed in other scripting languages so it's more inline with what the developer might expect.

**Comment by samyeyo** [comment]
You are absolutely right, thank you very much for this feedback.

I was not very satisfied with the implementation of the `Http:get()` method, especially on the two points you described (the inconsistency of the return value, and the impossibility of modifying the request headers before sending)

Your enhancement suggestion is now on my todo list.

Thank you again!
