### ISSUE TITLE
Final Window Creation in the First Executable Crashes

### ISSUE THREAD

**Issue by CraneStyle** [samyeyo/LuaRT#72]
At the point where you use QuickRT, performing the last command of the introduction win:show(). 

Expected: 
A window pops up with the title name of what I passed in when i created the window 

Result:
A window pops up with the title of what i expected, and immediately goes into a "Not responding" state, then shortly crashes QuickRT and the window at the same time.

**Comment by samyeyo** [comment]
Hi CraneStyle,

Thank you for the report.

The fact that the just created Window don't respond to the user is expected (user interaction is managed through the `ui.update()` method call), but it shouldn't crash (I have test it right now and it doesn't crash on my side).

Once you called `win:show()` in QuickRT, try to enter the following command : `ui.update(100000)` this will permit to move/resize the window without hanging the Window, but QuickRT will wait.

**Comment by CraneStyle** [comment]
I know I am not the best coder in the world, but in theory then when I
write a windows app with this, i would link ui.update() into the tick ? So
that it would get hit during the cycle ?

I am assuming that ui.update() is setting a timer that allows the Ui. TO
update for that period of time, but it yields at that point in code ?

**Comment by samyeyo** [comment]
> I know I am not the best coder in the world, but in theory then when I
> write a windows app with this, i would link ui.update() into the tick ? So
> that it would get hit during the cycle ?

Yes you are right, but QuickRT don't provide a "tick" to call ui.update() regularly... but it's a good idea 💡 

> I am assuming that ui.update() is setting a timer that allows the Ui. TO
> update for that period of time, but it yields at that point in code ?

Yes, after the time provided in `ui.update()` call, the execution come back to your Lua script (or to QuickRT in this case)

**Comment by CraneStyle** [comment]
Any chance you could post a small tutorial on using the studio provided to
create a persistent window and like a basic list or something?  Just
something thats like super basic that would cover making a super basic app
like Adding a name to list, would be AWESOME!

At the moment I have no idea how I would, in the studio, do that.  Also, I
attempted just to make the variation of the quick RT example of hte window
using STUDIO and got it to run when i hit the play, but when I tried
turning it into an executable and then run, the executable fails saying it
cant find a .dll or something I am somewhat confused by it.

**Comment by samyeyo** [comment]
> Any chance you could post a small tutorial on using the studio provided to
> create a persistent window and like a basic list or something?
Yes it's on my todo list !

> when I tried turning it into an executable and then run, the executable fails saying it
> cant find a .dll or something I am somewhat confused by it.
Generated executables depends on the Lua runtime `lua54.dll` to be executed. Just put a copy of this file (found in the `\bin` folder) to where you have your compiled executable.

**Comment by samyeyo** [comment]
_Update_ : 

I have an internal working version of QuickRT that calls `ui.update` periodicaly, refreshing the GUI while creating, resizing, ... widgets interactively from QuickRT.

Thank your for your feedback that leads me too this good idea 👍

**Comment by CraneStyle** [comment]
Awesome!

If I see anything else or get an example I think is worth anything ill pipe
it your way.

In your opinion, and use so far.  Do you ha e any suggestions for project
organization ?

With lua, I am used to a single script initializer, and running everything
else from modules.

And treating modules as class constructors / managers or pure function
libs.

Do you have a preferred or optimal organization?

Without just uploading code, do you have maybe pictures of how you would
organize a more complex application?

Finally,  are there any best practices you would recommend?

Also, I looked everywhere.  Is there a way to load a window within a
window?  Or do you have to have 2 windows communication with each other for
that kind of feature.

I was looking through Microsoft documentation, but it didn't really give me
any clues.

**Comment by samyeyo** [comment]
> In your opinion, and use so far.  Do you ha e any suggestions for project
> organization ?
> With lua, I am used to a single script initializer, and running everything
> else from modules.
> And treating modules as class constructors / managers or pure function
> libs.
> Do you have a preferred or optimal organization?

It depends of the project, but usually I'll keep with one script regrouping objects/functions that have the same goal. I tend to use submodules folder hierarchy when the application is complex.

> Also, I looked everywhere.  Is there a way to load a window within a
>window?  Or do you have to have 2 windows communication with each other for
> that kind of feature.

LuaRT don't support Window in other windows, but it's good idea. If I have time I will check what I can do
