### ISSUE TITLE
Buy you a coffee?

### ISSUE THREAD

**Issue by Jamtoad** [samyeyo/LuaRT#78]
Man, is there a way I can donate? I absolutely love this editor and its been my daily driver for almost 3 months now. Id love to be able to contribute to the development!

**Comment by samyeyo** [comment]
Thank you so much for your feedback on LuaRT.
I will put a "but me a coffee" link 👍🏻

**Comment by samyeyo** [comment]
I have Updated the README.md file to provide the link

**Comment by Jamtoad** [comment]
Thank you!
