### ISSUE TITLE
Is there a way for syntax highlighting in an Edit?

### ISSUE THREAD

**Issue by Dismalitie** [samyeyo/LuaRT#82]
I noticed that the LuaRT Studio's code workspace has syntax highlighting and was wondering wether the same effect could be acheived in your UI module. If not, then maybe you could implement officially like this:
```lua
local text = ui.Edit(win, "magenta, blue, green", 10, 10)
for i="magenta" in text do
     i:highlight("magenta" or "#FF00FF")
end
```
or
```lua
local text = ui.Edit(win, "magenta, blue, green", 10, 10)
text:highlight("magenta", "#FF00FF")
```

**Comment by samyeyo** [comment]
Hi Dismalitie,

`ui.Edit` widget don't have highlighting support out of the box, as it is based on Windows Richedit component.

But you can use syntax highlighting manualy as in the following example :
https://github.com/samyeyo/LuaRT/blob/master/examples/ui/syntax.wlua

**Comment by Dismalitie** [comment]
Thanks!
