### ISSUE TITLE
Question: How to access subelements of a table?

### ISSUE THREAD

**Issue by Dismalitie** [samyeyo/LuaRT#83]
So im probably dumb but how do I access subelements of a table?
I'm trying to set an icon but i can't figure it out...
Here's my src:
```lua
local win = ui.Window("astroIDE", "fixed", 800, 500)
local tree = ui.Tree(win, {["MyProject"] = {"init.astrosrc", ["Resources"] = {"res"}}}, 0, 0, 150, 400)
tree.style = "icons"
tree.items["MyProject"]:loadicon("icos\\main.ico")
tree.items["MyProject"].["init.astrosrc"]:loadicon("icos\\main.ico")
```

**Comment by samyeyo** [comment]
Sorry for the late reply, and probably you could find the answer to your question in the documentation with the properties `Tree.items` and `TreeItem.subitems`
