### ISSUE TITLE
UI refresh artifacts on window resizing

### ISSUE THREAD

**Issue by Dismalitie** [samyeyo/LuaRT#86]
While working on a project, I noticed that when resizing the window with `Window.width` or `Window.height` creates black visual artifacts in the section that is resizing. I beleive it is to do with the screen refresh and the `ui.update()` function. Here is some code that can be used to replicate the problem:
```lua
local ui = require("ui")
local win = ui.Window("UI refresh artifacts replication", 500, 500)
local button = ui.Button(win, "Click me!", 10, 10)
function button:onClick()
  repeat
    win.width = win.width+20
    sys.sleep(1)
  until win.width == 800
  button.enabled = false
end
win:show()
repeat ui.update() until not win.visible
```
![image](https://github.com/samyeyo/LuaRT/assets/118924562/08faf89d-522a-4ff9-b4f9-b0cf1fa4b49d)
This may also be a problem at my end with my screen, so here are my monitor specs in case you want to emulate them:

- Resolution; `1920x1080`
- Refresh rate; `74.97hz`
- Colour format; `RGB`
- Colour space; `SDR (Standard Dynamic Range)`
- Bit depth; `8-bit`

My graphics card is a `NVIDIA GeForce RTX 2080`
Thanks for reading! 👍

**Comment by samyeyo** [comment]
Hi Dismalitie,

Thank you for this report.
In fact it's not a bug : inside an UI event, the GUI is not updated.
If you change a widget property (size, position, color...) you need to update the UI using `ui.update()`

```
local ui = require("ui")
local win = ui.Window("UI refresh artifacts replication", 500, 500)
local button = ui.Button(win, "Click me!", 10, 10)
function button:onClick()
  repeat
    win.width = win.width+20
    ui.update() -- to update the ui after width has changed
  until win.width == 800
  button.enabled = false
end
win:show()
repeat ui.update() until not win.visible
```
It's not perfect but it's way better 😄

**Comment by samyeyo** [comment]
I have found another workaround to prevent this resizing problem, that will be available in next LuaRT release 👍

**Comment by Dismalitie** [comment]
Thanks!
